import { Suspense } from 'react';

import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';

import I18nProvider from '@/lib/i18n/i18n-provider';
import { ThemeProvider } from '@/lib/theme';
import ThemeSync from '@/lib/theme/theme-sync';

import './globals.css';

const nanumSquareNeo = localFont({
  src: '../../public/NanumSquareNeo-Variable.woff2',
  variable: '--font-nanum-square-neo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // interactiveWidget: 'resizes-content',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  console.log(cookieStore);
  const language = cookieStore.get('lang')?.value || 'en';

  return (
    <html suppressHydrationWarning>
      <body className={`${nanumSquareNeo.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={null}>
            <ThemeSync />
          </Suspense>
          <I18nProvider lang={language}>
            <div className="mobile-view">{children}</div>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
